# Create a consolidation class for L-ift kind of data

In [1]:
import pandas as pd
import numpy as np
import os;os.listdir()

['Consolidator.ipynb',
 'Consolidator_cosmas.ipynb',
 'Datafiles',
 'Outputs',
 'Surveys']

In [46]:
# the variables that will be used

report_date = "Mon Mar 28 2022" # the date of the data
#weeks_data = pd.read_excel("ECD Dates.xlsx") # the week files
datadir = 'Datafiles'

# define income variables
#Income----------------------------------------------------------------------------------------------------------------------------------
income_cols = {'respondent_id':"firm_id",
                        'income_report_data_id':'data_id',
                        'income_report_amount':'amount',
                        'income_report_currency':'currency',
                        'income_report_income_source_name':'reason_name',
                        'income_report_account':'account',
                        'income_report_date_received':'transaction_date',
                         'income_report_account_report_id':'transaction_id',
                        'income_report_transaction_type':'transaction_type',
                        'income_report_timeline':'timeline',
                        'income_report_payment_type':'payment_type',
                        'income_report_date_created':'date_created',
                        'income_report_last_updated':'date_last_updated',
                        'income_report_edit_count':'edit_count',
                        'income_report_surveyor':'surveyor',
                        'income_report_customer':'tool',
                        'income_report_description':'description',
                        "file":"file"}
#Expense -------------------------------------------------------------------------------------------------------------------------------
expense_cols= {'expense_report_account_report_id':'transaction_id',
                            'expense_report_data_id':'data_id',
                        'expense_report_amount': 'amount',
                        'expense_report_currency':'currency',
                        'expense_report_reason':'reason_name',
                        'expense_report_account':'account',
                        'expense_report_date':'transaction_date',
                        'expense_report_transaction_type':'transaction_type',
                        'expense_report_timeline':'timeline',
                        'expense_report_payment_type':'payment_type',
                        'expense_report_date_created':'date_created',
                            'expense_report_last_updated':'date_last_updated',
                        'expense_report_edit_count':'edit_count',
                        'respondent_id':"firm_id",
                        'expense_report_surveyor':'surveyor',
                        'expense_report_vendor':'tool',
                        'expense_report_description':'description',"file":"file"}
# Savings -----------------------------------------------------------------------------------------------------------------------------------
savings_col = {         'respondent_id':"firm_id",
                        'account_report_data_id':'data_id',
                        'account_report_amount':'amount',
                        'account_report_currency':'currency',
                        'account_report_account_name':'account',
                        'account_report_deposit/withdrawal':'reason_name',
                        'account_report_date':'transaction_date',
                        'account_report_data_type':'transaction_type',
                        'account_report_date_created':'date_created',
                        'account_report_last_updated':'date_last_updated',
                        'account_report_edit_count':'edit_count',
                        'account_report_surveyor':'surveyor',                
                       "file":"file",
                        'account_report_description':'description'}
# Repayments -------------------------------------------------------------------------------------------------------------------------------------------
repayment_col ={                'respondent_id':"firm_id",
                                'loan_taken_repayment_report_data_id':'data_id',
                                'loan_taken_repayment_report_repaid_amount':'amount',
                                'loan_taken_repayment_report_currency':'currency',
                                'loan_taken_repayment_report_source_name':'reason_name',
                                "loan_taken_repayment_report_account":'account',
                                'loan_taken_repayment_report_account_report_id':'transaction_id',
                                'loan_taken_repayment_report_date_paid':'transaction_date',
                                'loan_taken_repayment_report_date_created':'date_created',
                                'loan_taken_repayment_report_last_updated':'date_last_updated',
                                'loan_taken_repayment_report_edit_count':'edit_count',
                                'loan_taken_repayment_report_description':'description',
                                'loan_taken_repayment_report_surveyor':'surveyor',
                                "file":"file"}
# Loan Given ----------------------------------------------------------------------------------------------------------------------------------------------
given_col = {'respondent_id':"firm_id",
    'loan_given_repayment_report_description':'description',
                                'loan_given_repayment_report_data_id':'data_id',
                                'loan_given_repayment_report_account_report_id':'transaction_id',
                                'loan_given_repayment_report_repaid_amount':'amount',
                                'loan_given_repayment_report_currency':'currency',
                                'loan_given_repayment_report_source_name':'reason_name',
                                "loan_given_repayment_report_account":'account',
                                'loan_given_repayment_report_date':'transaction_date',
                                'loan_given_repayment_report_date_created':'date_created',
                                'loan_given_repayment_report_last_updated':'date_last_updated',
                                'loan_given_repayment_report_edit_count':'edit_count',
                                'loan_given_repayment_report_surveyor':'surveyor',"file":"file"}
#Employee ------------------------------------------------------------------------------------------------------------------------

# employee_col={                          'employee_payment_amount':'amount','respondent_id':'respondent_id','sector_type':'sector_type', 'gender':'gender', 'country_of_residence':'country_of_residence',
#                                         'firm_id':'firm_id',
#                                         'employee_payment_data_id':'data_id',
#                                         'employee_payment_currency':'currency',
#                                         'employee_payment_employee_name':'reason_name',
#                                         'employee_payment_type':'type',
#                                         'employee_payment_account':'account',
#                                         'employee_payment_transaction_type':'transaction_type',
#                                         'employee_payment_date':'transaction_date',
#                                         'employee_payment_date_created':'date_created',
#                                         # 'employee_payment_edit_count':'edit_count',
#                                         'employee_payment_surveyor':'surveyor','file':'file'}
# loantaken ----------------------------------------------------------------------------------------------------------------------------

taken_col={                               'loan_taken_data_id':'data_id','respondent_id':"firm_id",
          # 'sector_type':'sector_type', 
           'gender':'gender', 'country_of_residence':'country_of_residence',
                                        'loan_taken_name':'reason_name',
                                        'loan_taken_loan_type':'type',
                                        'loan_taken_description':'description',
                                        'loan_taken_payment_schedule':'payment_schedule',
                                        'loan_taken_amount_taken':'original_amount',
                                        'loan_taken_account':'account',
                                        'loan_taken_repayment_amount':'repaid_amount',
                                        'loan_taken_date':'transaction_date',
                                        'loan_taken_remaining_amount':'remaining_amount',
                                        'loan_taken_edit_count':'edit_count',
                                        'loan_taken_surveyor':'surveyor',"file":"file"}
# loangiven ----------------------------------------------------------------------------------------------------------------------------------
lgiven_col={                           'loan_given_data_id':'data_id','respondent_id':"firm_id",
            #'sector_type':'sector_type',
            'gender':'gender', 'country_of_residence':'country_of_residence',
                                        'loan_given_name':'reason_name',
                                        'loan_given_description':'description',
                                        'loan_given_payment_schedule':'payment_schedule',
                                        'loan_given_amount_given':'original_amount',
                                        'loan_given_repayment_amount':'repaid_amount',
                                        'loan_given_account':'account',
                                        'loan_given_date':'transaction_date',
                                        'loan_given_remaining_amount':'remaining_amount',
                                        'loan_given_edit_count':'edit_count',
                                        'loan_given_surveyor':'surveyor',"file":"file"}

In [29]:
import numpy as np

weeks = ["Week "+str(i) for i in list(range(1,21))]
def time_function(date):
    dates = weeks_data
    dates.columns = ['weeks', 'start_date', 'end_date']
    #dates["start_date"] = [str(i) for i in dates["start_date"]]
    #dates["end_date"]   = [str(i) for i in dates["end_date"]]
    try:
        for i,j in zip(dates["start_date"],dates["end_date"]):
            if i<=date<=j:
                dt = dates[(dates['start_date']==i) & (dates['end_date']==j)]

            else:
                pass
        return list(dt['weeks'])[0]
    except:
        return "check"


def cleaner(data):
        data.columns = [str(i) for i in data.columns]
        data.columns=data.columns.str.replace(' ','_')
        data.columns=data.columns.str.lower()
        #data.respondent_id = data.respondent_id.str.upper()
        return data
def week_date():
    df = consolidated.groupby(['firm_id', 'week']).\
        agg(start = ('transaction_date', 'min'), 
            end = ('transaction_date', 'max')).reset_index()
    return(df)
def week_date1():
    df = consolidated.groupby(['firm_id']).\
        agg(start = ('transaction_date', min), 
            end = ('transaction_date', 'max')).reset_index()
    return(df)
def add_ls():
    loan_schedule.week=''
    df = loan_schedule.merge(week_dates1, how='inner', on='firm_id')
    df.week = np.where(df.transaction_date<df.start, 'before_start', df.week)
    ls1=df[df.week=='before_start']# loans taken before the start of the study
    df=df[df.week!='before_start'].copy()# remove the above loans
    df = df.merge(week_dates, how='inner', on=['firm_id'])# merges loan data and possible weeks
    print(len(df.firm_id.unique()), len(ls1.firm_id.unique()), 
    len(loan_schedule.firm_id.unique()))
    df.week_x = np.where((df.transaction_date>=df.start_y) &
                (df.transaction_date<=df.end_y),df.week_y, 'check')# check  =  not found
    df[['firm_id', 'reason_name','transaction_date', 
        'start_y','end_y','week_x']]
    ls2 = df[df.week_x!='check'].drop_duplicates()# all matched loans less those not matched
    ls2['week']=ls2.week_x
    ls2['frame'] = 'ls2'
    ls3 = df[df.week_x=='check'].drop_duplicates(subset=['firm_id',
    'reason_name'])
    print(len(ls2), len(ls3))
    ls3 = ls3.merge(ls2[['firm_id','reason_name','frame']], how = 'left',
                    on = ['firm_id','reason_name'])
    ls3 = ls3[ls3.frame.isnull()==True]
    ls3['week']=ls3.week_x
    ls3=ls3.drop(['frame','start_x', 'end_x', 'week_y','week_y',
                    'start_y', 'end_y'], axis=1)
    ls2=ls2.drop(['frame','start_x', 'end_x', 'week_y','week_y',
                    'start_y', 'end_y'], axis=1)
    print(len(ls1),len(ls2), len(ls3))
    ls = ls1.append([ls2,ls3]).copy()
    ls['frame'] = 'ls'
    len(ls)

    df = loan_schedule.merge(ls[['firm_id','reason_name','frame']],
            how='left', on = ['firm_id','reason_name']).copy()
    ls4 = df[df.frame.isnull()==True]
    ls4 = ls4.drop('frame', axis=1)
    print(len(ls1),len(ls2), len(ls3), len(ls4))
    ls = ls.append(ls4).copy()
    ls['amount'] = ls.original_amount
    print(len(ls), len(loan_schedule))
    return(ls)

class Consolidator:
    def __init__(self,report_date,
                # weeks_data,
                 income,expense,savings,repayments,given,
                # employee,
                 taken,lgiven):
        self.report_date = report_date
        #self.week_data = weeks_data
        self.income = income
        self.expense = expense
        self.savings = savings  
        self.repayment = repayments
        self.given = given
        #self.employee = employee
        self.loantaken = taken
        self.loangiven = lgiven

    def income_normalize(self):
        data = self.income.copy()
        data = cleaner(data)
        data['file']='income'
        data1 = data[list(income_cols.keys())].copy()
        data1=data1.rename(columns=income_cols)
        print(f"Normalized income shape:{data1.shape}")
        return  data1
    def expense_normalize(self):
        data = self.expense.copy()
        data = cleaner(data)
        data['file']='expense'
        data1 = data[list(expense_cols.keys())].copy()
        data1=data1.rename(columns=expense_cols)
        print(f"Normalized expense shape:{data1.shape}")
        return  data1
    def savings_normalize(self):
        data = self.savings.copy()
        data = cleaner(data)
        data['file']='savings'
        data1 = data[list(savings_col.keys())].copy()
        data1=data1.rename(columns=savings_col)
        print(f"Normalized savings shape:{data1.shape}")
        return  data1
    def repayment_normalize(self):
        data = self.repayment.copy()
        data = cleaner(data)
        data['file']='loans_taken_repayment'
        data1 = data[list(repayment_col.keys())].copy()
        data1=data1.rename(columns=repayment_col)
        print(f"Normalized loans_taken_repayment_repayments shape:{data1.shape}")
        return  data1
    def given_normalize(self):
        data = self.given.copy()
        data = cleaner(data)
        data['file']='loans_given_repayment'
        data1 = data[list(given_col.keys())].copy()
        data1=data1.rename(columns=given_col)
        print(f"Normalized loans_given_repayment_repayments shape:{data1.shape}")
        return  data1
    def employee_normalize(self):
        data = self.employee.copy()
        data = cleaner(data)
        data['file']='expense'
        data1 = data[list(employee_col.keys())].copy()
        data1=data1.rename(columns=employee_col)
        print(f"Normalized employee payments shape:{data1.shape}")
        return  data1
    def loantaken_normalize(self):
        data = self.loantaken.copy()
        data = cleaner(data)
        data['file']='loans_taken'
        data1 = data[list(taken_col.keys())].copy()
        data1=data1.rename(columns=taken_col)
        data1 = data1.drop_duplicates(subset=['firm_id','reason_name'],  keep='first')
        print(f"Normalized Loan taken shape:{data1.shape}")
        return  data1
    def loangiven_normalize(self):
        data = self.loangiven.copy()
        data = cleaner(data)
        data['file']='loans_taken'
        data1 = data[list(lgiven_col.keys())].copy()
        data1=data1.rename(columns=lgiven_col)
        data1 = data1.drop_duplicates(subset=['firm_id','reason_name'],  keep='first')
        print(f"Normalized Loan given shape:{data1.shape}")
        return  data1

## <font color = "darkgreen">Consolidate for Mali</font>

In [25]:
income = pd.read_excel(datadir +"/Income Report - Mali Thu Jul 14 08_26_21 2022.xlsx",sheet_name = 'Income Reports');print("Income:",income.shape)
income["firm_id"] = income["Respondent ID"]
expense = pd.read_excel(datadir +f'/Expense Report - Mali Thu Jul 14 08_26_18 2022.xlsx', sheet_name = 'Expense Reports');print("Expense:",expense.shape)
savings = pd.read_excel(datadir +f'/Account Report - Mali Thu Jul 14 08_26_15 2022.xlsx', sheet_name = 'Account Reports');print("Savings:",savings.shape)
repayments = pd.read_excel(datadir +f'/Loan Taken Report - Mali Thu Jul 14 08_26_10 2022.xlsx', sheet_name = 'Loan Repayment Reports');print("Loan taken repayments",repayments.shape)
given = pd.read_excel(datadir +f'/Loan Given Report - Mali Thu Jul 14 08_26_13 2022.xlsx', sheet_name = 'Loan given repayments');print("Loan given repayments",given.shape)
#employee = payments = pd.read_excel(datadir +f'/Employee Report - {report_date}.xlsx',sheet_name = 'Employee payments');print("Employee repayments",employee.shape)
taken = pd.read_excel(datadir +f'/Loan Taken Report - Mali Thu Jul 14 08_26_10 2022.xlsx', sheet_name = "Loan's Taken");print("loan_taken:",taken.shape);print('loantaken:',taken.shape)
lgiven = pd.read_excel(datadir +f'/Loan Given Report - Mali Thu Jul 14 08_26_13 2022.xlsx',sheet_name = "Loans given");print("loan given:",lgiven.shape)

Income: (9289, 28)
Expense: (14746, 28)
Savings: (4564, 23)
Loan taken repayments (21, 23)
Loan given repayments (0, 23)
loan_taken: (18, 30)
loantaken: (18, 30)
loan given: (0, 29)

In [31]:
cleaner(expense).head(1)

,respondent_id,name,email,phone_number,gender,age,number_of_children,marital_status,country_of_residence,citizenship,...,expense_report_surveyor,expense_report_vendor,expense_report_timeline,expense_report_transaction_type,expense_report_payment_type,expense_report_date_created,expense_report_last_updated,expense_report_edit_count,expense_report_description,expense_report_tag
0,3849,Mohamed Sangare,mohamedsamgare1@gmail.com,22379204313,Male,29,0,Married,Mali,Mali,...,NaN,NaN,Full payment,NaN,NaN,2021-01-18,2021-01-18,0,NaN,NaN

In [67]:

def consolidator_country():
        consol = Consolidator(report_date = report_date,
                #weeks_data = weeks_data,
                income = income,
                expense = expense,
                savings = savings,
                repayments = repayments,
                given  = given,
                #employee = employee,
                taken = taken,
                lgiven = lgiven)

        data = [
                consol.income_normalize(),
                consol.expense_normalize(),
                consol.savings_normalize(),
                consol.repayment_normalize(),
                consol.given_normalize(),
                #consol.employee_normalize()
                ]
        consolidated = pd.concat(data);print(consolidated.shape)
        consolidated.head()
        consolidated.transaction_type = np.where((consolidated.file=='savings'),'cash',
                                        consolidated.transaction_type)
        consolidated.file = np.where((consolidated.file=='savings') & 
        (consolidated.reason_name=='Deposited'), 'savings_deposit', consolidated.file)
        consolidated.file = np.where((consolidated.file=='savings') & 
        (consolidated.reason_name=='Withdrawn'), 'savings_withdrawal', consolidated.file)

        # load data
        data = [consol.loantaken_normalize(),consol.loangiven_normalize()]
        loan_schedule = pd.concat(data)
        loan_schedule = loan_schedule.drop(["repaid_amount","remaining_amount"],1)
        loan_schedule = loan_schedule.rename(columns = {"original_amount":"amount"})
        consolidated = consolidated.append(loan_schedule, sort=False)

        # further cleaning
        consolidated["transaction_date"] = pd.DatetimeIndex(consolidated["transaction_date"])
        consolidated["week"] = ["Week "+ str(i.isocalendar()[1]) for i in consolidated["transaction_date"]]
        consolidated = consolidated[['firm_id', 'country_of_residence','data_id','amount','currency',
                                'transaction_date','account','reason_name','description', 'file',"week"]]
        consolidated.head()

        # finalizing teh consolidation 

        file_lst = ['expense', 'savings_deposit', 'loans_taken_repayment','loans_given']

        consolidated['amount1'] = np.where(consolidated.file.isin(file_lst),consolidated.amount*-1,
        consolidated.amount)

        consolidated = consolidated[['firm_id', 'country_of_residence','data_id','amount','currency',
                                'transaction_date','account','reason_name','description', 'file',"week"]]
        return consolidated
Mali = consolidator_country();print(Mali.shape)

Normalized income shape:(9289, 18)
Normalized expense shape:(14746, 18)
Normalized savings shape:(4564, 14)
Normalized loans_taken_repayment_repayments shape:(21, 14)
Normalized loans_given_repayment_repayments shape:(0, 14)
(28620, 18)
Normalized Loan taken shape:(12, 16)
Normalized Loan given shape:(0, 15)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_17828\1035502436.py:33: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  loan_schedule = loan_schedule.drop(["repaid_amount","remaining_amount"],1)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_17828\1035502436.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  consolidated = consolidated.append(loan_schedule, sort=False)

(28632, 11)

,firm_id,country_of_residence,data_id,amount,currency,transaction_date,account,reason_name,description,file,week
0,3849,NaN,IN00077319,2000,XOF,2021-01-11,NaN,Vente Nourriture,NaN,income,Week 2
1,3849,NaN,IN00079538,3000,XOF,2021-01-12,NaN,Vente Nourriture,NaN,income,Week 2
2,3849,NaN,IN00077320,3000,XOF,2021-01-12,NaN,Vente Nourriture,NaN,income,Week 2
3,3849,NaN,IN00077321,2700,XOF,2021-01-13,NaN,Vente Nourriture,NaN,income,Week 2
4,3849,NaN,IN00079539,3500,XOF,2021-01-13,NaN,Vente Nourriture,NaN,income,Week 2

In [64]:
# consolidated['transaction_date'] = pd.DatetimeIndex(consolidated['transaction_date'])
# consolidated['transaction_date'] = pd.DatetimeIndex(consolidated['transaction_date'])
# consolidated['week'] = list(map(time_function,consolidated['transaction_date']))
# consolidated.groupby(["week"]).data_id.count()
#consolidated["file1"] = np.where(consolidated.data_id.str.contains("EE"),"employee",consolidated.file)
file_lst = ['expense', 'savings_deposit', 'loans_taken_repayment','loans_given']

consolidated['amount1'] = np.where(consolidated.file.isin(file_lst),consolidated.amount*-1,
consolidated.amount)

consolidated = consolidated[['firm_id', 'country_of_residence','data_id','amount','currency',
                             'transaction_date','account','reason_name','description', 'file',"week"]]
print(consolidated.shape)

(28632, 11)